### ISSUE TITLE
Print more clear `login success` information

### ISSUE THREAD

**Issue by zzxwill** [aliyun/acr-login#13]
In my test, when successfully logging to ACR, it will print the information as below:

```
Run aliyun/acr-login@v1
  with:
    login-server: https://kubevela-registry.cn-hangzhou.cr.aliyuncs.com
    username: ***
    password: ***
    region-id: cn-hangzhou
  env:
    BUCKET: ***
    ENDPOINT: ***
    ACCESS_KEY: ***
    ACCESS_KEY_SECRET: ***
    ARTIFACT_HUB_REPOSITORY_ID: ***

DOCKER_CONFIG environment variable is set
```

How about we appending some similar information as below?

```
...

Successfully login to ACR.
```
