### ISSUE TITLE
Action failed to get authorization token with error: Error: code: 404, , requestid: 

### ISSUE THREAD

**Issue by vettalwu** [aliyun/acr-login#15]
Hi，I use the following config to login ACR:

```
 - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          region-id: "cn-hangzhou"
          access-key-id: "${{ secrets.ACK_ACCESS_KEY_ID }}"
          access-key-secret: "${{ secrets.ACK_ACCESS_KEY_SECRET }}"
```

It returns the following error:

![image](https://user-images.githubusercontent.com/92501707/159853319-ae506d93-a972-4c77-83f9-0c60f45154ef.png)

Is there something I missed?
