### ISSUE TITLE
acr-login action fail when the acr repo is set to private

### ISSUE THREAD

**Issue by JoeZhangOk** [aliyun/acr-login#29]
My workflow code is here: 
```
    - name: Install Python dependencies
      shell: bash
      run: pip install alibabacloud_sts20150401 requests

    - name: Configure Ali credentials
      id: ali-credentials
      uses: aliyun/configure-aliyun-credentials-action@v1
      with:
        role-to-assume: "acs:ram::${{ inputs.core_account }}:role/daytona-developer"
        oidc-provider-arn: "acs:ram::${{ inputs.core_account }}:oidc-provider/code.connected.bmw"

    - name: Login to ACR
      id: login-acr
      uses: aliyun/acr-login@v1
      with:
        login-server: 'https://orbit-registry.cn-beijing.cr.aliyuncs.com'
        region-id: 'cn-beijing'
        access-key-id: ${{ steps.ali-credentials.outputs.aliyun-access-key-id }}
        access-key-secret: ${{ steps.ali-credentials.outputs.aliyun-access-key-secret }}
        security-token: ${{ steps.ali-credentials.outputs.aliyun-security-token }}
        instance-id: ${{ inputs.acr_instance_id }}

    - name: Pull terraform util image from ACR
      env:
        REGISTRY: orbit-registry.cn-beijing.cr.aliyuncs.com/default
        REPOSITORY: daytona/public/util-terraform
        IMAGE_TAG: alicloud-1.6.6
      shell: bash
      run: |
        docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG util-terraform-ali:1.6.6
        docker images
```
if the acr repo is public, it works. But if I change the repo to private, pulling will fail

![Image](https://github.com/user-attachments/assets/513ff0f5-7478-48a5-8891-2f0a993b469a)

If i don't use this action and use docker login command, it also works:
```
    - name: Install Python dependencies
      shell: bash
      run: pip install alibabacloud_sts20150401 requests

    - name: Configure Ali credentials
      id: ali-credentials
      uses: aliyun/configure-aliyun-credentials-action@v1
      with:
        role-to-assume: "acs:ram::${{ inputs.core_account }}:role/daytona-developer"
        oidc-provider-arn: "acs:ram::${{ inputs.core_account }}:oidc-provider/code.connected.bmw"

    - name: Login to ACR
      run: |
        wget https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz
        tar -xzvf aliyun-cli-linux-latest-amd64.tgz
        AUTH_JSON=$(./aliyun cr GetAuthorizationToken --region cn-beijing --InstanceId ${{ inputs.acr_instance_id }} \
          --version 2018-12-01 --endpoint cr.cn-beijing.aliyuncs.com)
        AUTH_TOKEN=$(echo $AUTH_JSON | jq -r .AuthorizationToken)
        TEMP_USERNAME=$(echo $AUTH_JSON | jq -r .TempUsername)
        echo $AUTH_TOKEN | docker login -u $TEMP_USERNAME -p $AUTH_TOKEN orbit-registry.cn-beijing.cr.aliyuncs.com
      shell: bash

    - name: Pull terraform util image from ACR
      env:
        REGISTRY: orbit-registry.cn-beijing.cr.aliyuncs.com/default
        REPOSITORY: daytona/public/util-terraform
        IMAGE_TAG: alicloud-1.6.6
      shell: bash
      run: |
        docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG util-terraform-ali:1.6.6
        docker images
```

**Comment by incubator4** [comment]
Same issue, and better steps (maybe?)
```
      - uses: aliyun/configure-aliyun-credentials-action@v1
        id: aliyun-auth
        with:
          role-to-assume: "acs:ram::<account-id>:role/docker"
          oidc-provider-arn: "acs:ram::<account-id>:oidc-provider/github"

      - name: setup aliyun cli
        uses: aliyun/setup-aliyun-cli-action@v1

      - name: get acr credential
        id: acr-cred
        run: |
          RESPONSE=$(aliyun cr GetAuthorizationToken --region us-east-1 --InstanceId ${{ env.ACR_INSTANCE_ID }})
          TEMP_USERNAME=$(echo "$RESPONSE" | jq -r '.TempUsername')
          AUTH_TOKEN=$(echo "$RESPONSE" | jq -r '.AuthorizationToken')

          echo "::add-mask::$AUTH_TOKEN"

          echo "username=$TEMP_USERNAME" >> $GITHUB_OUTPUT
          echo "password=$AUTH_TOKEN" >> $GITHUB_OUTPUT

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: <account-registry>
          username: ${{ steps.acr-cred.outputs.username }}
          password: ${{ steps.acr-cred.outputs.password }}
```
